"""Define constants for the RSP UI Validator."""
TAP_APPLICATION = "tap"
SSOTAP_APPLICATION = "ssotap"
TAP_SCHEMA_QUERY = "SELECT TOP 1 * FROM TAP_SCHEMA.tables"
STILTS_URL = "https://www.star.bristol.ac.uk/mbt/stilts/stilts.jar"
STILTS_FILENAME = "stilts.jar"
